name: Test JDK_Gen

on:
  workflow_dispatch:        
  
jobs:
  build:
    runs-on: macos-15
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'graalvm'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Setup prebuild
      run: |
          sudo mv /Library/Developer/CommandLineTools/SDKs/* /tmp
          sudo mv /Applications/Xcode.app /Applications/Xcode.app.bak
          sudo mv /Applications/Xcode_16.2.app /Applications/Xcode.app
          sudo xcode-select -switch /Applications/Xcode.app
          xcodebuild -version
          brew install autogen autoconf automake libtool pkg-config wget isl cloog cmake gpg ant maven mpfr libmpc repo premake texinfo
          mkdir moe-ci
          cd moe-ci
          repo init -u https://github.com/multi-os-engine/manifest.git -b moe-svm
          repo sync -j$(sysctl -n hw.ncpu)
          
    - name: Build MOE
      run: |
          cd moe-ci/moe/
          ./gradlew :moe-core:moe.apple:moe.core.native:svm.openjdk:jdk_gensrc || true
          cat /Users/runner/work/moe-gha/moe-gha/moe-ci/svm/labs-openjdk-21/build/labsjdk/make-support/failure-logs
          
      
